title: C2PA Node.js library
description: >- # this means to ignore newlines until "baseurl:"
  API documentation for the Content Authenticity Initiative Node.js library.
baseurl: "/c2pa-node-v2" # the subpath of your site, e.g. /blog
url: "https://crandmck.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
remote_theme: "jekyll/minima@1e8a445"
#theme: minima


defaults:
  - scope:
      path: "classes"
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "functions"
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "interfaces"
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "type-aliases"
      type: "pages"
    values:
      layout: "page"
